name = "joosu-selledu"
main = "server/index.js"
compatibility_date = "2024-01-01"

[env.production]
routes = [
  { pattern = "api.selledu.com/*", zone_name = "selledu.com" }
]

[vars]
NODE_ENV = "production"

