name = "selledu-pages"
compatibility_date = "2024-01-01"
pages_build_output_dir = "client/build"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "selledu-db"
database_id = "acef10dc-3987-4483-83ff-235b537d49a0"

# R2 Bucket binding for images
[[r2_buckets]]
binding = "IMAGES"
bucket_name = "selledu-images"
preview_bucket_name = "selledu-images"

[env.production]
name = "selledu"

# D1 Database binding for production
[[env.production.d1_databases]]
binding = "DB"
database_name = "selledu-db"
database_id = "acef10dc-3987-4483-83ff-235b537d49a0"

# R2 Bucket binding for production
[[env.production.r2_buckets]]
binding = "IMAGES"
bucket_name = "selledu-images"
preview_bucket_name = "selledu-images"
